- worthapp/index.html
Still need to make Marc's interactives functional here.
> Add basic html5 app - PMT #110305

- worthapp/css/worth.css
- worthapp/index.html
- worthapp/js/common.js
- worthapp/js/feeling.js
- worthapp/js/myth-fact.js
Added functionality to the feelings activity and fixed some style
issues.
> html5 app updates - PMT #110305

- worthapp/index.html
I'm working on the html5 app for now because I can't get the keyboard
to pop up in iBooks on text form inputs.
> Add basic worth hierarchy - PMT #110583

- worthapp/index.html
This fixes an aligment issue when using the table of contents
> attach id's to slide elements

- worthapp/index.html
- worthapp/js/social-support.js
> Add social support map activity skeleton - PMT #110583

- worthapp/css/worth.css
- worthapp/index.html
> Safety Plan Summary updates

- scripts/build_tree.py
- scripts/templates/nav.xhtml
- scripts/templates/page.xhtml
- scripts/templates/toc.ncx
- scripts/tree.json
- worthbook/EPUB/js/common.js
- worthbook/EPUB/js/safety.js
- worthbook/EPUB/js/social-support.js
- worthbook/EPUB/nav.xhtml
- worthbook/EPUB/package.opf
- worthbook/EPUB/s0101.xhtml
- worthbook/EPUB/s0102.xhtml
- worthbook/EPUB/s0103.xhtml
- worthbook/EPUB/s0104.xhtml
- worthbook/EPUB/s0105.xhtml
- worthbook/EPUB/s0106.xhtml
- worthbook/EPUB/s0107.xhtml
- worthbook/EPUB/s0108.xhtml
- worthbook/EPUB/s0109.xhtml
- worthbook/EPUB/s0110.xhtml
- worthbook/EPUB/s0111.xhtml
- worthbook/EPUB/s0112.xhtml
- worthbook/EPUB/s0113.xhtml
- worthbook/EPUB/s0114.xhtml
- worthbook/EPUB/s0115.xhtml
- worthbook/EPUB/toc.ncx
This creates the epub skeleton (table of contents + individual pages)
using the file at scripts/tree.json.
> Add epub tree generator

- scripts/templates/index.html
- worthapp/index.html
Based on phonegap's recommendations:
http://docs.phonegap.com/tutorials/develop/hello-world-explained/
> Update meta tags

- .travis.yml
- Makefile
- js.mk
* update makefile to include worthapp build step
* remove the epub check, since we're focusing on the html5 app now
> makefile updates

- scripts/build_worthapp.py
- scripts/templates/myth-fact.html
- worthapp/index.html
- worthapp/js/src/common.js
- worthapp/js/src/myth-fact.js
- worthapp/js/src/reflection.js
- worthapp/js/src/safety.js
- worthapp/js/src/self-talk.js
- worthapp/js/src/social-support.js
Still more content to add here
> Add more myth/fact content + introduce initActivityPanels()

- worthapp/css/worth.css
- worthapp/index.html
- worthapp/js/src/swiper-setup.js
> design pre-flight

- scripts/templates/index.html
- worthapp/css/worth.css
- worthapp/index.html
> navigation tweaks

- scripts/tree.json
- worthapp/index.html
According to Jess this has been finalized by the client.
> Update table of contents based on spreadsheet

- scripts/templates/summing-it-up-3.html
- scripts/tree.json
- worthapp/index.html
The grammar here is kind of awkward, but I'll take that up with Jess.
> Summing it up 3/24 - PMT #111345

- scripts/templates/ssnm.html
- worthapp/index.html
> Add card layout for ssnm activity - PMT #111518

- templates/reducing-risks-2.html
This reflects Tim's edits. I also added the writing icon.
> updated the goals and added icon

- tree.json
please update the toc with these changes
> removed extra exclamation points and parens

- tree.json
> added missing s1 video ids

- templates/feelings.html
made the "swipe left" message text and alignment match the reflect on a character activities
> updated style of move on message

- templates/safety-plan-4.html
changed final button to say "I want to start over" and added "you're done" alert
> added "you're done" message to last button

- tree.json
moved several risk reduction pages to the right spot, added some missing video ids, changed some titles
> updates added pages and changed a title

- templates/feelings.html
- templates/i-am-worth-it.html
- templates/index.html
- templates/my-commitment-to-me.html
- templates/myth-fact.html
- templates/page.html
- templates/protective-behaviors.html
- templates/reducing-risks-2.html
- templates/reflect-amanda.html
- templates/reflect-charlene.html
- templates/reflect-mia.html
- templates/reflect-rasheeda.html
- templates/reflect-sofia.html
- templates/safety-plan-4.html
- templates/safety.html
- templates/self-talk-4.html
- templates/self-talk.html
- templates/sofias-trauma.html
- templates/ssnm.html
- templates/strengthening-support.html
- templates/summing-it-up-1.html
- templates/summing-it-up-2.html
- templates/summing-it-up-3.html
- templates/summing-it-up-4.html
- templates/summing-it-up-5.html
- templates/things-i-am-proud-of.html
- templates/video.html
- worthapp/css/worth.css
- worthapp/index.html
> Design 062817

- tree.json
- worthapp/index.html
> title case for slide titles

- Makefile
- scripts/build_worthapp.py
- worthapp/css/worth.css
- worthapp/index.html
- worthapp/js/src/swiper-setup.js
> Add session links in nav + add py sentinal setup in Makefile

- templates/self-talk-4.html
The second video is now correct and I changed an answer from correct to incorrect
> updated second video and fixed answer

- templates/check-out-what-youve-learned.html
some feedback didn't sound good and I fixed. please check panel 7 - i changed to displaying right/wrong with a single alert feedback message. I'm not sure I've got all the necessary div tags in there.
> fixed green/red backgrounds, changed some wording

- templates/feelings.html
- templates/i-am-worth-it.html
- templates/my-commitment-to-me.html
- templates/protective-behaviors.html
- templates/ssnm.html
- tree.json
- worthapp/index.html
* Remove extraneous headings
* Consistent next/back behavior
* Consistent move on messaging
> Activity cleanup

- templates/self-talk-4.html
- templates/self-talk.html
- worthapp/index.html
- worthapp/js/src/self-talk.js
* Consistent next/back behavior
* Fixing video (negative self-talk was repeated)
> Rasheeda's self-talk

- templates/self-talk-4.html
- templates/self-talk.html
- worthapp/css/worth.css
- worthapp/index.html
- worthapp/js/src/self-talk.js
* Fix Rasheeda panel html
* Make common navigational elements consistent
> Self Talk: tweaks

- templates/what-did-we-learn-2.html
- templates/what-did-we-learn-3.html
- templates/what-did-we-learn-4.html
- templates/what-did-we-learn-5.html
- worthapp/index.html
* fix feedback font size
* Add "Swipe to Move On" at end
* Add in alert-infos to the final feedback
> What Did We Learn: polish

- scripts/build_worthapp.py
- templates/title-page.html
- tree.json
- worthapp/css/worth.css
- worthapp/index.html
* add a title page at the beginning of each section
* don't display the title page in the TOC. (The session title links to this page)
* custom template
> Session Title Pages

- templates/reflect-amanda.html
- templates/reflect-charlene.html
- templates/reflect-mia.html
- templates/reflect-rasheeda.html
- templates/reflect-sofia.html
- worthapp/index.html
Replace navigation back / next.
"That's my answer" pattern
Orient "Great Job!" swipe to move on into the Next button position
> Reflect activities PMT#: 111609

- templates/my-commitment-to-me.html
- worthapp/css/worth.css
- worthapp/index.html
* consistent next/back behavior
* tuning for a landscape layout
> Polish: My Commitment to Me

- templates/myth-fact.html
- worthapp/index.html
- worthapp/js/src/myth-fact.js
* consistent button text
* consolidate answer feedback
* remove redundant information
> Polish Myth / Fact

- templates/i-am-worth-it.html
- worthapp/css/worth.css
- worthapp/index.html
- worthapp/js/src/i-am-worth-it.js
- Hide name tag before selection, rehide when it goes back
- Standardize "Back", "Swipe forwards"
- Re-apportion columns into thirds
> I Am Worth It exercise

- tree.json
> Update tree.json - shortened page titles

- templates/self-talk.html
removed one answer choice from the negative quiz
> Update self-talk.html 

- templates/fantasy-menu.html
> changed question on how adventurous are you

- worthapp/js/src/fantasy-menu.js
please check this to make sure I didn't leave off a quote or something - I'm not sure how javascript really works
> changed the scoring feedback

- templates/my-commitment-to-me.html
made grammar match, changed feedback list
> my commitment to me changes

- templates/protective-behaviors.html
- worthapp/css/worth.css
- worthapp/index.html
- worthapp/js/src/protective-behaviors.js
This applies to sections 2.20 and 5.7
This commit standardizes the navigation, and removes the disable state
so users can change thier answers.
> "Stuff I Do" PMT#: 111620

- templates/ssnm.html
- worthapp/css/worth.css
- worthapp/index.html
- Add back/next navigation
- Emotional & Practical support should not be checked by default
- 'Very Close' & 'Me" labels are too small
- line up check boxes and add a little separation
- on last slide, add some top margin to button, remove period in button
text
> SSNM Activites; PMT#: 111627

- worthapp/js/src/common.js
On device debugging showed an issue with the es6 "let" syntax. Removing to
resolve.
> Removing es6 syntax

- templates/feelings.html
- worthapp/index.html
This commit:
- Replace "I want to try again" with Back, floated left
- Swipe to move on orients Right
> Feelings Station PMT#: 111614

- templates/check-out-what-youve-learned.html
- templates/what-did-we-learn-1.html
- templates/what-did-we-learn-2.html
- templates/what-did-we-learn-3.html
- templates/what-did-we-learn-4.html
- templates/what-did-we-learn-5.html
- worthapp/index.html
- worthapp/js/src/check-out-what-youve-learned.js
- worthapp/js/src/common.js
- worthapp/js/src/what-did-we-learn.js
What Did We Learn quizzes & Check What I've Learned quiz
* Show a mild alert to users when no answer is selected.
* Do not let the user proceed forward until the answer is selected.
* Factoring out some common code to use across activities
> Revisit quiz behavior

- worthapp/css/worth.css
Override default next button alignment
> Next button alignment

- tree.json
- worthapp/index.html
> The last page

- templates/popping-our-problems.html
- templates/practicing-pop.html
- worthapp/index.html
- worthapp/js/src/pop.js
* feedback styling
* require users to answer questions, giving feedback accordingly
* consistent next/back/swipe to move forward
> POP activities polish

- worthapp/js/src/common.js
> Quiz common - mark answers correct

- templates/self-talk-4.html
- templates/self-talk.html
- worthapp/index.html
- worthapp/js/src/self-talk.js
Sessions 3.9 (Rasheeda) and 4.8 (Sofia)
* Make subheads consistent
* Require users to answer questions and provide appropriate feedback
* Rasheeda: 1st page should be "Begin" rather than Next
> Self-talk activities polish

- templates/practicing-negotiation-1.html
- worthapp/index.html
- worthapp/js/src/practicing-negotiation-1.js
- continue button on first page - should be next
- needs back and next throughout
- ok buttons still inside feedback
- all questions are supposed to be checkboxes and not radio buttons
- back/next buttons need to be above the fold when there is a video
- user must answer question then disable
- final page should swipe messaging and such
> Practicing Negotiation - polish PMT#: 111680

- templates/fantasy-menu.html
- worthapp/css/worth.css
- worthapp/index.html
- worthapp/js/src/fantasy-menu.js
* Fix missing title andsection label
* Consistent navigation
* Pull progress bar (2-page interactive)
* Add title & feedback if user chooses not to respond
> Adventurous - polish

- templates/sofias-trauma.html
- worthapp/index.html
- worthapp/js/src/trauma.js
* smaller font on feedback
* move swipe message to next button position
* Initial button should be "Begin" and centered.
* Fix Back button not working
* Require user response with appropriate feedback. Disable input once answered.
> Sofia's Trauma - Polish

- templates/safety-plan-4.html
- worthapp/index.html
* remove begin button and replace with "next"
* final page needs "back" instead of "I want to start over"
* put swipe message in right spot
> Writing down your safety plan - polish

- templates/protective-behaviors.html
- worthapp/index.html
- worthapp/js/src/protective-behaviors.js
* Fix padding on the 2nd page feedback infobox
* Remove some extraneous code
> Stuff I Do - polish

- templates/assessing-my-relationships.html
- worthapp/index.html
- worthapp/js/src/assessing-relationships.js
* Resolve flow issues on page 2
* Verified videos are all present
* Users are required to answer questions
* Consistent next/back behavior
> Assessing Relationships

- worthapp/js/src/swiper-setup.js
Removing the TOC page requires removing some +1/-1 adjustments
> Adjust swiper logic

- worthapp/js/src/fantasy-menu.js
* take care of default case
* fix some grammer & tense
> How Adventurous Are You - tweaks

- templates/ssnm.html
- worthapp/css/worth.css
- worthapp/index.html
- worthapp/js/src/ssnm.js
This consolidates the input content.  It also adjust the layout to take
up less space.
> SSNM Consolidate Form inputs PMT# 111742

- worthapp/js/src/common.js
- worthapp/js/src/swiper-setup.js
Video loads occasionally seem to fail. The video ready state comes through
as 1 (HAVE_METADATA - metadata for the audio/video is ready). If the video
state is not 4 when the video comes into view, force a load to ensure things
are ready to go.
> Optimize video loading

- templates/assessing-my-relationships.html
- templates/myth-fact.html
- templates/popping-our-problems.html
- templates/practicing-negotiation-1.html
- templates/practicing-pop.html
- templates/protective-behaviors.html
- templates/safety-plan-4.html
- templates/safety.html
- templates/self-talk-4.html
- templates/self-talk.html
- templates/video.html
- worthapp/index.html
This makes worth behave much better in desktop chrome - I'm
experimenting here to see how it will behave in phonegap on the lenovo
and asus devices.
> Turn off video pre-loading

- tree.json
- worthapp/index.html
This commit replaces a video that had the green screen left in. It also
changes the grammer of the title of the corresponding section for
clarity.
> Swap in video

- LICENSE
added description of WORTH transitions
> update to the license
